/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { AppointmentUpdateManyWithoutUsersInput } from "./AppointmentUpdateManyWithoutUsersInput";
import { ValidateNested, IsOptional, IsString } from "class-validator";
import { Type } from "class-transformer";
import { BotUpdateManyWithoutUsersInput } from "./BotUpdateManyWithoutUsersInput";
import { CrmDataUpdateManyWithoutUsersInput } from "./CrmDataUpdateManyWithoutUsersInput";
import { LanguageSettingUpdateManyWithoutUsersInput } from "./LanguageSettingUpdateManyWithoutUsersInput";
import { IsJSONValue } from "../../validators";
import { GraphQLJSON } from "graphql-type-json";
import { InputJsonValue } from "../../types";
import { SubscriptionUpdateManyWithoutUsersInput } from "./SubscriptionUpdateManyWithoutUsersInput";

@InputType()
class UserUpdateInput {
  @ApiProperty({
    required: false,
    type: () => AppointmentUpdateManyWithoutUsersInput,
  })
  @ValidateNested()
  @Type(() => AppointmentUpdateManyWithoutUsersInput)
  @IsOptional()
  @Field(() => AppointmentUpdateManyWithoutUsersInput, {
    nullable: true,
  })
  appointments?: AppointmentUpdateManyWithoutUsersInput;

  @ApiProperty({
    required: false,
    type: () => BotUpdateManyWithoutUsersInput,
  })
  @ValidateNested()
  @Type(() => BotUpdateManyWithoutUsersInput)
  @IsOptional()
  @Field(() => BotUpdateManyWithoutUsersInput, {
    nullable: true,
  })
  bots?: BotUpdateManyWithoutUsersInput;

  @ApiProperty({
    required: false,
    type: () => CrmDataUpdateManyWithoutUsersInput,
  })
  @ValidateNested()
  @Type(() => CrmDataUpdateManyWithoutUsersInput)
  @IsOptional()
  @Field(() => CrmDataUpdateManyWithoutUsersInput, {
    nullable: true,
  })
  crmDataItems?: CrmDataUpdateManyWithoutUsersInput;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  email?: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  firstName?: string | null;

  @ApiProperty({
    required: false,
    type: () => LanguageSettingUpdateManyWithoutUsersInput,
  })
  @ValidateNested()
  @Type(() => LanguageSettingUpdateManyWithoutUsersInput)
  @IsOptional()
  @Field(() => LanguageSettingUpdateManyWithoutUsersInput, {
    nullable: true,
  })
  languageSettings?: LanguageSettingUpdateManyWithoutUsersInput;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  lastName?: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  password?: string;

  @ApiProperty({
    required: false,
  })
  @IsJSONValue()
  @IsOptional()
  @Field(() => GraphQLJSON, {
    nullable: true,
  })
  roles?: InputJsonValue;

  @ApiProperty({
    required: false,
    type: () => SubscriptionUpdateManyWithoutUsersInput,
  })
  @ValidateNested()
  @Type(() => SubscriptionUpdateManyWithoutUsersInput)
  @IsOptional()
  @Field(() => SubscriptionUpdateManyWithoutUsersInput, {
    nullable: true,
  })
  subscriptions?: SubscriptionUpdateManyWithoutUsersInput;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  username?: string;
}

export { UserUpdateInput as UserUpdateInput };
