/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { CrmDataService } from "../crmData.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { CrmDataCreateInput } from "./CrmDataCreateInput";
import { CrmData } from "./CrmData";
import { CrmDataFindManyArgs } from "./CrmDataFindManyArgs";
import { CrmDataWhereUniqueInput } from "./CrmDataWhereUniqueInput";
import { CrmDataUpdateInput } from "./CrmDataUpdateInput";

@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class CrmDataControllerBase {
  constructor(
    protected readonly service: CrmDataService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}
  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Post()
  @swagger.ApiCreatedResponse({ type: CrmData })
  @nestAccessControl.UseRoles({
    resource: "CrmData",
    action: "create",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  @swagger.ApiBody({
    type: CrmDataCreateInput,
  })
  async createCrmData(
    @common.Body() data: CrmDataCreateInput
  ): Promise<CrmData> {
    return await this.service.createCrmData({
      data: {
        ...data,

        bot: data.bot
          ? {
              connect: data.bot,
            }
          : undefined,

        user: data.user
          ? {
              connect: data.user,
            }
          : undefined,
      },
      select: {
        bot: {
          select: {
            id: true,
          },
        },

        createdAt: true,
        email: true,
        id: true,
        phoneNumber: true,
        updatedAt: true,

        user: {
          select: {
            id: true,
          },
        },
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get()
  @swagger.ApiOkResponse({ type: [CrmData] })
  @ApiNestedQuery(CrmDataFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "CrmData",
    action: "read",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async crmDataItems(@common.Req() request: Request): Promise<CrmData[]> {
    const args = plainToClass(CrmDataFindManyArgs, request.query);
    return this.service.crmDataItems({
      ...args,
      select: {
        bot: {
          select: {
            id: true,
          },
        },

        createdAt: true,
        email: true,
        id: true,
        phoneNumber: true,
        updatedAt: true,

        user: {
          select: {
            id: true,
          },
        },
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: CrmData })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "CrmData",
    action: "read",
    possession: "own",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async crmData(
    @common.Param() params: CrmDataWhereUniqueInput
  ): Promise<CrmData | null> {
    const result = await this.service.crmData({
      where: params,
      select: {
        bot: {
          select: {
            id: true,
          },
        },

        createdAt: true,
        email: true,
        id: true,
        phoneNumber: true,
        updatedAt: true,

        user: {
          select: {
            id: true,
          },
        },
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: CrmData })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "CrmData",
    action: "update",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  @swagger.ApiBody({
    type: CrmDataUpdateInput,
  })
  async updateCrmData(
    @common.Param() params: CrmDataWhereUniqueInput,
    @common.Body() data: CrmDataUpdateInput
  ): Promise<CrmData | null> {
    try {
      return await this.service.updateCrmData({
        where: params,
        data: {
          ...data,

          bot: data.bot
            ? {
                connect: data.bot,
              }
            : undefined,

          user: data.user
            ? {
                connect: data.user,
              }
            : undefined,
        },
        select: {
          bot: {
            select: {
              id: true,
            },
          },

          createdAt: true,
          email: true,
          id: true,
          phoneNumber: true,
          updatedAt: true,

          user: {
            select: {
              id: true,
            },
          },
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: CrmData })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "CrmData",
    action: "delete",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async deleteCrmData(
    @common.Param() params: CrmDataWhereUniqueInput
  ): Promise<CrmData | null> {
    try {
      return await this.service.deleteCrmData({
        where: params,
        select: {
          bot: {
            select: {
              id: true,
            },
          },

          createdAt: true,
          email: true,
          id: true,
          phoneNumber: true,
          updatedAt: true,

          user: {
            select: {
              id: true,
            },
          },
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
